Thenext web
GraceOyiza/Thenext-web pull request #2
Opened 2020-07-14 05:20 UTC by mcihadkurel

### The Next Web Clone
**İn this project:**
1-) We created media queries.
2-) We updated it for 3 kinds of screen sizes.
3-) Added 2 different navbar for top and bottom.
4-) Used background image for the main section.
5-) Background images cover each fill.
6-) Stickler errors fixed
7-) Html validator issues fixed.
8-) Footer icons have 50% border-radius.

2020-07-14 17:06 UTC, bertil291utn commented
**Status:** Changes requested 🔴  :shipit: ? Not yet

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

Your work is amazing you master it GitHub Flow you have a professional README file. (Check to improve [section](##To_improve))



### Mandatory changes

- [ ] Check the linter files you have stickler config change to [GitHub actions](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [ ] Check your README file live demo section. Fix your markdown syntax


  <img src="https://user-images.githubusercontent.com/24902525/87446759-5a24ad80-c5bf-11ea-8d30-fc1c89117924.png" alt="image" style="zoom:67%;" />

- [ ] Add `overflow-x:hidden` property to avoid horizontal scrolling

##### Small screen
- [ ] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to seach icon) ([link to page](https://thenextweb.com/))

- [ ] All images take the maximum width and are are aligned in one column ([link to page](https://thenextweb.com/))

- [ ] It aligns 1 articles per row ([link to page](https://thenextweb.com/))

   Each articles has a cover image on the left side and title on the right side of the row ([link to page](https://thenextweb.com/))

|                       ACTUAL WEB PAGE                        |                            YOURS                             |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
| ![image](https://user-images.githubusercontent.com/24902525/87447514-4af22f80-c5c0-11ea-99d8-d6f9cf4a33c1.png) | ![image](https://user-images.githubusercontent.com/24902525/87447288-049cd080-c5c0-11ea-87dc-3a6a4a869cad.png) |



##### Medium screen

- [ ] TWN logo appears at the leftmost part ([link to page](https://thenextweb.com/))

- [ ] And also your width page doesn't look great.

![image](https://user-images.githubusercontent.com/24902525/87446845-77597c00-c5bf-11ea-9506-154e1866c89d.png)





##### Large screen

- [ ] It contains one bigger image on the leftmost part of the row (around two-thirds of the width) ([link to page](https://thenextweb.com/))
- [ ]  It contains two smaller images on the rightmost part of the row (one above another) ([link to page](https://thenextweb.com/))

<img src="https://user-images.githubusercontent.com/24902525/87448112-03b86e80-c5c1-11ea-88d7-3c5f6c465495.png" alt="image" style="zoom:67%;" />

- [ ] It aligns 4 articles per row ([link to page](https://thenextweb.com/))

  <img src="https://user-images.githubusercontent.com/24902525/87448245-2e0a2c00-c5c1-11ea-80c5-111dc5b52e03.png" alt="image" style="zoom:67%;" />

 

- [ ] It aligns 3 category boxes per row ([link to page](https://thenextweb.com/))

<img src="https://user-images.githubusercontent.com/24902525/87448393-67429c00-c5c1-11ea-87cf-909f795467fc.png" alt="image" style="zoom:67%;" />

- [ ] It aligns 4 deals per row ([link to page](https://thenextweb.com/))
- [ ] Check your elements is overlapping other ones

<img src="https://user-images.githubusercontent.com/24902525/87448484-89d4b500-c5c1-11ea-8f06-5b1e6edaf982.png" alt="image" style="zoom:67%;" />



- [ ] **It does not change through breakpoints** ([link to page](https://thenextweb.com/))

|                       ACTUAL WEB PAGE                        |                            YOURS                             |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
| ![image](https://user-images.githubusercontent.com/24902525/87451451-7c212e80-c5c5-11ea-9feb-edbfd3578dca.png) | ![image](https://user-images.githubusercontent.com/24902525/87451573-a8d54600-c5c5-11ea-8fc3-9d4e3fff7b36.png) |

### Summary

Please check again your project when you have a small screen approach.

<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-15 13:24 UTC, GraceOyiza commented
The errors have been corrected 
1.  Live demo fixed.
2. Corrected overlapping images.
3. All screen sizes fixed.
4. Linters errors fixed.

2020-07-15 14:14 UTC, bertil291utn requested changes
**Status:** Changes requested 🔴  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Good job on your changes, however, some requests are not changed.

- [ ] You're still forgetting use GitHub Actions to check the linters

### Small screen


Check again [original web page](https://thenextweb.com/) with a small screen and try to compare it with your approach. Work on all changes should be the same as the original one.

- [ ] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to search icon) ([link to page](https://thenextweb.com/))

- [ ] All images take the maximum width and are are aligned in one column ([link to page](https://thenextweb.com/))

- **Latest news section**

- [ ] It aligns 1 articles per row ([link to page](https://thenextweb.com/))
- [ ] Each articles has a cover image on the left side and title on the right side of the row ([link to page](https://thenextweb.com/))

- **Latest funding section**

- [ ] It aligns 1 articles per row ([link to page](https://thenextweb.com/))

- **Categories (Apps, Gear, Tech, etc) section**

- [ ] It aligns 1 category box per row ([link to page](https://thenextweb.com/))

- **Latest deals section**

- [ ] It aligns 1 deal per row ([link to page](https://thenextweb.com/))



|                       ACTUAL WEB PAGE                        |                        YOUR APPROACH                         |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
| ![image](https://user-images.githubusercontent.com/24902525/87552232-04134100-c677-11ea-9f1f-d70f82af74d7.png) | ![image](https://user-images.githubusercontent.com/24902525/87552265-12615d00-c677-11ea-8781-bf7d2fbe003f.png) |

### Medium screen


- **Latest Funding section**

- [ ]   It aligns 3 articles per row ([link to page](https://thenextweb.com/))

  <img src="https://user-images.githubusercontent.com/24902525/87554135-61a88d00-c679-11ea-944b-0057b0c5135a.png" alt="image" style="zoom:67%;" />


- **Top 3 articles section**

- [ ] It contains search icon at the rightmost side of sub-navigation row ([link to page](https://thenextweb.com/))

<img src="https://user-images.githubusercontent.com/24902525/87554560-e2678900-c679-11ea-967d-f397e561b2af.png" alt="image" style="zoom:67%;" />

- [ ]  It contains TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/))
![image](https://user-images.githubusercontent.com/24902525/87554958-691c6600-c67a-11ea-8a15-37174074b577.png)




### Footer


- [ ] **It does not change through breakpoints** ([link to page](https://thenextweb.com/))

- [ ] It doesn't contain social media icons vertically and horizontally aligned ([link to page](https://thenextweb.com/))

### General requirements


- [ ] Work on the details you have to approach a clone. You have to on each screening approach (small, medium and large) not only in this section check also other sections

![image](https://user-images.githubusercontent.com/24902525/87554335-a03e4780-c679-11ea-9fa8-884bcf6df389.png)



### Summary


- Please try to work most on a small screen approach, you have put effort into it.

- You should be the same as the original one, follow all details and check your page don't break any element.

<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-15 14:14 UTC, bertil291utn commented on style.css
> +}
## CSS styles should use media queries for 2 breakpoints (screenshot from Pathwright)

- [ ] No small breakpoint as it is mobile-first and the base styles are for the mobile screen. (Screenshot on mobile-first approach from Pathwright)
    - medium: min-width around 768px
    - large: min-width 1024px

2020-07-16 17:36 UTC, GraceOyiza commented
All errors fixed.
Github action created.

2020-07-16 18:09 UTC, expjazz requested changes
## Status: Changes requested :recycle: 

### Hello Team. You did a great job :clap: 

However, there are still changes to be done in order to let this project even better. You can check them in the notes below. I would say that generally, the page looks good, but you still need to work on the details, font sizes, and what shows and not shows depending on the screen-sizes.

 Try to make this more like the original. I can see that you improved from the last review and we are almost there. Just a few details more.

#### On mobile

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87705097-c1835e80-c773-11ea-8701-538e3094a290.png) | ![image](https://user-images.githubusercontent.com/61479648/87705132-cfd17a80-c773-11ea-9195-ee5d6df2dfe2.png) |

- [ ] The search bar needs to be more close to the left end of the page. 
 

- [ ] There is no hamburger menu

- [ ] The navbar is occupying space from the first article. 

#### Large screen

- [ ] Pay attention to this TNW logo. It should be invisible on the large screen.


| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87705586-803f7e80-c774-11ea-8be2-dd54a83c2e77.png) | ![image](https://user-images.githubusercontent.com/61479648/87705667-a533f180-c774-11ea-88d1-94fc3121f2fd.png) |

- [ ] You have linter errors


### Kindly fix them  and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:


_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-16 18:09 UTC, expjazz commented on index.html
> +         <div class="get">
You have a few problems here. Try to make this more as like the original. I can see that you improved from the last review and we are almost there. Just a few details more.

#### On mobile

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87705097-c1835e80-c773-11ea-8701-538e3094a290.png) | ![image](https://user-images.githubusercontent.com/61479648/87705132-cfd17a80-c773-11ea-9195-ee5d6df2dfe2.png) |

- [ ] The search bar needs to be more close to the left end of the page. 
 

- [ ] There is no hamburger menu

- [ ] The navbar is occupying space from the first article. 

#### Large screen

- [ ] Pay attention to this TNW logo. It should be invisible on the large screen.

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87705586-803f7e80-c774-11ea-8be2-dd54a83c2e77.png) | ![image](https://user-images.githubusercontent.com/61479648/87705667-a533f180-c774-11ea-88d1-94fc3121f2fd.png) |

2020-07-17 06:34 UTC, GraceOyiza commented
All changes inputted.

2020-07-17 06:50 UTC, elmejdki requested changes
# status: require changes
## Great job so far team :clap: :100: :+1: you are almost there.

- [ ] please fix the linter errors:
![image](https://user-images.githubusercontent.com/34653764/87757129-0950c700-c802-11ea-9228-53812e29672d.png)

### Please make the required changes before you submit another code review.
## happy Coding :tophat:

2020-07-17 06:54 UTC, mcihadkurel commented
You can see there must be still stickler errors. But its just a bug. First TSE suggested us change stickler with github action. So we removed stickler file in repo.

2020-07-17 08:00 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Great job guys you have made an awesome work by applying all the required changes by the previous TSE's.

now you can merge to master your project is approved.

## Happy Coding :tophat:

2020-07-17 08:00 UTC, merged